programa soma inicio
    real a;
    inteiro b;
    inteiro c;
    booleano e;
    real d;

    e = verdadeiro;
    b = 3;
    d = 2 + a * b / a;

    e = (1 < 2) & 2 < 3 | 1 < 0;
    //escreva(e);

    enquanto (a < b & b != 0) inicio
        real z;
        a = a + 1;
        enquanto (a < b & b != 0) inicio
            real z;
            real y;
            a = a + 1;
            y = 0.0;
        fim;
    fim;

    se (1 != a) inicio
       real w;
        escreva(d);
    fim;
fim.